name: continuous-integration example

on:
  push:
    branches:
      master

jobs:
  build-and-test-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Build with gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Run tests
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew test

